package com.jiang.meskill.dao;

import com.jiang.meskill.dataobject.OrderDO;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Apr 14 12:48:10 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Apr 14 12:48:10 CST 2022
     */
    int insert(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Apr 14 12:48:10 CST 2022
     */
    int insertSelective(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Apr 14 12:48:10 CST 2022
     */
    OrderDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Apr 14 12:48:10 CST 2022
     */
    int updateByPrimaryKeySelective(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Thu Apr 14 12:48:10 CST 2022
     */
    int updateByPrimaryKey(OrderDO row);
}