package com.jiang.meskill.dao;

import com.jiang.meskill.dataobject.SequenceDO;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Apr 14 13:55:27 CST 2022
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Apr 14 13:55:27 CST 2022
     */
    int insert(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Apr 14 13:55:27 CST 2022
     */
    int insertSelective(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Apr 14 13:55:27 CST 2022
     */
    SequenceDO selectByPrimaryKey(String name);
    SequenceDO getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Apr 14 13:55:28 CST 2022
     */
    int updateByPrimaryKeySelective(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Apr 14 13:55:28 CST 2022
     */
    int updateByPrimaryKey(SequenceDO row);
}